title: Linnea Kirby
author: Linnea Kirby
email: linnea@linneakirby.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Linnea Kirby.

github_username:  linneakirby

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d %b %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
 #- about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
